services:
  tester:
    build:
      context: .
      target: terminator-tester-local
    working_dir: /cyberdyne
    volumes:
      - .:/cyberdyne
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    environment:
      TERM: ${TERM:-}
