#!/bin/sh
find . -name '*.py' \
-o -name '*.java' \
-o -iname '*.[CH]' \
-o -name '*.cpp' \
-o -name '*.cc' \
-o -name '*.hpp'  \
> .git/cscope.files

# -b: just build
# -q: create inverted index
cscope -b -q -i .git/cscope.files -f .git/cscope.out
