#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --extra=+f --tag-relative -Rf.git/tags.$$ --exclude=.git
#ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql
# ctags --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++
mv .git/tags.$$ .git/tags
