#!/bin/bash

path_to_submodule=$1

if [[ $# -eq 0 ]] ; then
  echo 'ERROR no path_to_submodule specified'
  exit 1
fi

if [ ! -d "$path_to_submodule" ]; then
  echo "ERROR path_to_submodule: '${path_to_submodule}' not found"
  exit 1
fi

# Remove the submodule entry from .git/config
git submodule deinit -f ${path_to_submodule}

# Remove the submodule directory from the superproject's .git/modules directory
rm -rf .git/modules/${path_to_submodule}

# Remove the entry in .gitmodules and remove the submodule directory located at ${path_to_submodule}
git rm -f ${path_to_submodule}
