name: Run Quality Checks and Publish PR
on:
  pull_request:
    branches: [main]

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    name: Run Quality Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run Tests
        uses: ./.github/actions/run-make
        id: run-make
        with:
          target: test
